# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_cvt.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1000, 750)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_database_setting = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_database_setting.setFont(font)
        self.pushButton_database_setting.setObjectName("pushButton_database_setting")
        self.verticalLayout.addWidget(self.pushButton_database_setting)
        self.pushButton_time_ini = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_time_ini.setFont(font)
        self.pushButton_time_ini.setObjectName("pushButton_time_ini")
        self.verticalLayout.addWidget(self.pushButton_time_ini)
        self.pushButton_serial_setting = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_serial_setting.setFont(font)
        self.pushButton_serial_setting.setObjectName("pushButton_serial_setting")
        self.verticalLayout.addWidget(self.pushButton_serial_setting)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_tableName = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_tableName.setFont(font)
        self.comboBox_tableName.setObjectName("comboBox_tableName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_tableName)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton_select = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_select.setFont(font)
        self.pushButton_select.setObjectName("pushButton_select")
        self.verticalLayout.addWidget(self.pushButton_select)
        self.pushButton_test = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_test.setFont(font)
        self.pushButton_test.setObjectName("pushButton_test")
        self.verticalLayout.addWidget(self.pushButton_test)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(118, 549, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_db_data = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_db_data.setAlternatingRowColors(True)
        self.tableWidget_db_data.setObjectName("tableWidget_db_data")
        self.tableWidget_db_data.setColumnCount(0)
        self.tableWidget_db_data.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_db_data, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CVT运行态势在线评估和风险预警系统"))
        self.groupBox.setTitle(_translate("MainWindow", "设置"))
        self.pushButton_database_setting.setText(_translate("MainWindow", "数据库配置"))
        self.pushButton_time_ini.setText(_translate("MainWindow", "站点配置"))
        self.pushButton_serial_setting.setText(_translate("MainWindow", "串口设置"))
        self.label.setText(_translate("MainWindow", "表名称"))
        self.pushButton_select.setText(_translate("MainWindow", "显示数据"))
        self.pushButton_test.setText(_translate("MainWindow", "测试"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据表显示"))
        self.label_2.setText(_translate("MainWindow", "CVT运行态势在线评估和风险预警系统"))

