# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_station_initialize.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_station_initialize(object):
    def setupUi(self, station_initialize):
        station_initialize.setObjectName("station_initialize")
        station_initialize.resize(278, 195)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(station_initialize.sizePolicy().hasHeightForWidth())
        station_initialize.setSizePolicy(sizePolicy)
        station_initialize.setSizeGripEnabled(True)
        self.gridLayout_4 = QtWidgets.QGridLayout(station_initialize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(station_initialize)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit_stationID = QtWidgets.QLineEdit(station_initialize)
        self.LineEdit_stationID.setObjectName("LineEdit_stationID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_stationID)
        self.verticalLayout.addLayout(self.formLayout)
        self.groupBox_send_rawdata = QtWidgets.QGroupBox(station_initialize)
        self.groupBox_send_rawdata.setObjectName("groupBox_send_rawdata")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_send_rawdata)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_interval_send_rawdata = QtWidgets.QLabel(self.groupBox_send_rawdata)
        self.label_interval_send_rawdata.setObjectName("label_interval_send_rawdata")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_interval_send_rawdata)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_send_rawdata_h = QtWidgets.QSpinBox(self.groupBox_send_rawdata)
        self.spinBox_send_rawdata_h.setMaximum(72)
        self.spinBox_send_rawdata_h.setObjectName("spinBox_send_rawdata_h")
        self.horizontalLayout.addWidget(self.spinBox_send_rawdata_h)
        self.label_4 = QtWidgets.QLabel(self.groupBox_send_rawdata)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBox_send_rawdata_m = QtWidgets.QSpinBox(self.groupBox_send_rawdata)
        self.spinBox_send_rawdata_m.setMaximum(59)
        self.spinBox_send_rawdata_m.setProperty("value", 15)
        self.spinBox_send_rawdata_m.setObjectName("spinBox_send_rawdata_m")
        self.horizontalLayout.addWidget(self.spinBox_send_rawdata_m)
        self.label_3 = QtWidgets.QLabel(self.groupBox_send_rawdata)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_send_rawdata)
        self.groupBox_2 = QtWidgets.QGroupBox(station_initialize)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_mlab_h = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_mlab_h.setMinimum(0)
        self.spinBox_mlab_h.setMaximum(72)
        self.spinBox_mlab_h.setProperty("value", 24)
        self.spinBox_mlab_h.setObjectName("spinBox_mlab_h")
        self.horizontalLayout_2.addWidget(self.spinBox_mlab_h)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spinBox_mlab_m = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_mlab_m.setMaximum(59)
        self.spinBox_mlab_m.setProperty("value", 0)
        self.spinBox_mlab_m.setObjectName("spinBox_mlab_m")
        self.horizontalLayout_2.addWidget(self.spinBox_mlab_m)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.pushButton = QtWidgets.QPushButton(station_initialize)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(station_initialize)
        QtCore.QMetaObject.connectSlotsByName(station_initialize)

    def retranslateUi(self, station_initialize):
        _translate = QtCore.QCoreApplication.translate
        station_initialize.setWindowTitle(_translate("station_initialize", "站点配置"))
        self.Label.setText(_translate("station_initialize", "  站号"))
        self.groupBox_send_rawdata.setTitle(_translate("station_initialize", "原始数据发送"))
        self.label_interval_send_rawdata.setText(_translate("station_initialize", "时间间隔"))
        self.label_4.setText(_translate("station_initialize", "h"))
        self.label_3.setText(_translate("station_initialize", "m"))
        self.groupBox_2.setTitle(_translate("station_initialize", "Matlab处理及数据发送"))
        self.label_6.setText(_translate("station_initialize", "时间间隔"))
        self.label_7.setText(_translate("station_initialize", "h"))
        self.label_8.setText(_translate("station_initialize", "m"))
        self.pushButton.setText(_translate("station_initialize", "修改"))

