# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_serial_setting.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_serial_setting(object):
    def setupUi(self, serial_setting):
        serial_setting.setObjectName("serial_setting")
        serial_setting.resize(416, 177)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(serial_setting.sizePolicy().hasHeightForWidth())
        serial_setting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        serial_setting.setFont(font)
        serial_setting.setSizeGripEnabled(True)
        self.gridLayout_5 = QtWidgets.QGridLayout(serial_setting)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_receive = QtWidgets.QGroupBox(serial_setting)
        self.groupBox_receive.setObjectName("groupBox_receive")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_receive)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_comName_receive1 = QtWidgets.QLabel(self.groupBox_receive)
        self.label_comName_receive1.setObjectName("label_comName_receive1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_comName_receive1)
        self.comboBox_comName_receive1 = QtWidgets.QComboBox(self.groupBox_receive)
        self.comboBox_comName_receive1.setObjectName("comboBox_comName_receive1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_comName_receive1)
        self.label_Baudrate_receive = QtWidgets.QLabel(self.groupBox_receive)
        self.label_Baudrate_receive.setObjectName("label_Baudrate_receive")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Baudrate_receive)
        self.comboBox_Baudrate_receive = QtWidgets.QComboBox(self.groupBox_receive)
        self.comboBox_Baudrate_receive.setEditable(True)
        self.comboBox_Baudrate_receive.setObjectName("comboBox_Baudrate_receive")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_Baudrate_receive)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_close_receive = QtWidgets.QPushButton(self.groupBox_receive)
        self.pushButton_close_receive.setObjectName("pushButton_close_receive")
        self.gridLayout.addWidget(self.pushButton_close_receive, 0, 1, 1, 1)
        self.pushButton_open_receive = QtWidgets.QPushButton(self.groupBox_receive)
        self.pushButton_open_receive.setObjectName("pushButton_open_receive")
        self.gridLayout.addWidget(self.pushButton_open_receive, 0, 0, 1, 1)
        self.pushButton_refresh_receive = QtWidgets.QPushButton(self.groupBox_receive)
        self.pushButton_refresh_receive.setObjectName("pushButton_refresh_receive")
        self.gridLayout.addWidget(self.pushButton_refresh_receive, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_receive)
        self.groupBox_receive_2 = QtWidgets.QGroupBox(serial_setting)
        self.groupBox_receive_2.setObjectName("groupBox_receive_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_receive_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_comName_send = QtWidgets.QLabel(self.groupBox_receive_2)
        self.label_comName_send.setObjectName("label_comName_send")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_comName_send)
        self.comboBox_comName_send = QtWidgets.QComboBox(self.groupBox_receive_2)
        self.comboBox_comName_send.setObjectName("comboBox_comName_send")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_comName_send)
        self.label_Baudrate_send = QtWidgets.QLabel(self.groupBox_receive_2)
        self.label_Baudrate_send.setObjectName("label_Baudrate_send")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Baudrate_send)
        self.comboBox_Baudrate_send = QtWidgets.QComboBox(self.groupBox_receive_2)
        self.comboBox_Baudrate_send.setEditable(True)
        self.comboBox_Baudrate_send.setObjectName("comboBox_Baudrate_send")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_Baudrate_send)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_close_send = QtWidgets.QPushButton(self.groupBox_receive_2)
        self.pushButton_close_send.setObjectName("pushButton_close_send")
        self.gridLayout_2.addWidget(self.pushButton_close_send, 0, 1, 1, 1)
        self.pushButton_open_send = QtWidgets.QPushButton(self.groupBox_receive_2)
        self.pushButton_open_send.setObjectName("pushButton_open_send")
        self.gridLayout_2.addWidget(self.pushButton_open_send, 0, 0, 1, 1)
        self.pushButton_refresh_send = QtWidgets.QPushButton(self.groupBox_receive_2)
        self.pushButton_refresh_send.setObjectName("pushButton_refresh_send")
        self.gridLayout_2.addWidget(self.pushButton_refresh_send, 1, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_receive_2)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(serial_setting)
        QtCore.QMetaObject.connectSlotsByName(serial_setting)

    def retranslateUi(self, serial_setting):
        _translate = QtCore.QCoreApplication.translate
        serial_setting.setWindowTitle(_translate("serial_setting", "串口设置"))
        self.groupBox_receive.setTitle(_translate("serial_setting", "接收串口"))
        self.label_comName_receive1.setText(_translate("serial_setting", "串口号"))
        self.label_Baudrate_receive.setText(_translate("serial_setting", "波特率"))
        self.pushButton_close_receive.setText(_translate("serial_setting", "关闭串口"))
        self.pushButton_open_receive.setText(_translate("serial_setting", "打开串口"))
        self.pushButton_refresh_receive.setText(_translate("serial_setting", "刷新串口"))
        self.groupBox_receive_2.setTitle(_translate("serial_setting", "发送串口"))
        self.label_comName_send.setText(_translate("serial_setting", "串口号"))
        self.label_Baudrate_send.setText(_translate("serial_setting", "波特率"))
        self.pushButton_close_send.setText(_translate("serial_setting", "关闭串口"))
        self.pushButton_open_send.setText(_translate("serial_setting", "打开串口"))
        self.pushButton_refresh_send.setText(_translate("serial_setting", "刷新串口"))

